steps:
  - name: node:18
    entrypoint: npm
    args: ["install"]
    id: install

  - name: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0"
    entrypoint: /cloud-sql-proxy
    args:
      [
        "${_CLOUDSQL_CONNECTION}",
        "--address=0.0.0.0",
        "--port=5432"
      ]
    background: true

  - name: "busybox"
    args: ["sh", "-c", "sleep 5"]


  - name: node:18
    entrypoint: sh
    args:
      - -c
      - |
        npx prisma migrate deploy
    env:
      - DATABASE_URL=postgresql://postgres:${_DB_PASSWORD}@127.0.0.1:5432/postgres?schema=public&connect_timeout=60

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t", "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA",
        "."
      ]


  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA"
      ]


  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "${_SERVICE_NAME}",
        "--image", "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA",
        "--region", "${_REGION}",
        "--platform", "managed",
        "--allow-unauthenticated",
        "--add-cloudsql-instances", "${_CLOUDSQL_CONNECTION}",
        "--set-env-vars",
        "DATABASE_URL=postgresql://postgres:${_DB_PASSWORD}@localhost/postgres?host=/cloudsql/${_CLOUDSQL_CONNECTION}&schema=public"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
