steps:
  # 1. Install Node dependencies
  - name: node:18
    entrypoint: npm
    args: ["install"]
    id: install

  # 2. Start Cloud SQL Proxy in the background
  # This listens on localhost:5432 and tunnels to your Google Cloud SQL instance
  - name: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
    args:
      - "--structured-logs"
      - "--port=5432"
      - "${_CLOUDSQL_CONNECTION}"
    id: proxy
    waitFor: ['-'] # Start immediately, don't wait for previous steps

  # 3. Run Prisma migration (Connects via TCP to Localhost Proxy)
  - name: node:18
    entrypoint: sh
    args:
      - -c
      - |
        # Wait a few seconds for the proxy to initialize
        sleep 5 
        npx prisma migrate deploy
    env:
      # NOTE: For the BUILD step, we use 127.0.0.1 (TCP), not the socket path
      - DATABASE_URL=postgresql://postgres:${_DB_PASSWORD}@127.0.0.1:5432/postgres?schema=public
    waitFor: ['install', 'proxy'] # Wait for install to finish and proxy to start

  # 4. Build the Docker image
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA", "."]
    waitFor: ['install'] # Can start as soon as install is done (doesn't need migration)

  # 5. Push the Docker image
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA"]

  # 6. Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "${_SERVICE_NAME}",
        "--image", "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA",
        "--region", "${_REGION}",
        "--platform", "managed",
        "--allow-unauthenticated",
        "--add-cloudsql-instances", "${_CLOUDSQL_CONNECTION}",
        # NOTE: For CLOUD RUN, we switch back to the Socket path. This is correct here.
        "--set-env-vars", "DATABASE_URL=postgresql://postgres:${_DB_PASSWORD}@/postgres?host=/cloudsql/${_CLOUDSQL_CONNECTION}&schema=public",
        "--set-env-vars", "PORT=4000"
      ]

options:
  logging: CLOUD_LOGGING_ONLY